[alias]
build-esp32 = "build --target riscv32imc-unknown-none-elf --features esp32"
release-esp32 = "build --release --target riscv32imc-unknown-none-elf --features esp32"

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x"]

[env]
ESP_LOG = "info"

[unstable]
build-std = ["core", "alloc"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
